### ISSUE TITLE
Does this method support proto3?

### ISSUE THREAD

**Issue by zhy2020** [nopnop2002/esp-idf-protocol-buffer#1]
Does this method support proto3?

**Comment by nopnop2002** [comment]
ESP-IDF takes advantage of this.
https://github.com/protobuf-c/protobuf-c/tree/abc67a11c6db271bedbb9f58be85d6f4e2ea8389

**Comment by nopnop2002** [comment]
proto3 is not supported.
I get this error when building the farm.

```
../main/main.c:23:12: error: 'AMessage' {aka 'struct _AMessage'} has no member named 'has_b'
   23 |         msg.has_b = 1;
      |            ^
../main/main.c:41:17: error: 'AMessage' {aka 'struct _AMessage'} has no member named 'has_b'
   41 |         if (msg2->has_b) // handle optional field
      |                 ^~
```

**Comment by zhy2020** [comment]
> proto3

Is there any other way to support proto3 on ESP32?

**Comment by nopnop2002** [comment]
I don't know.

You may be able to get some information by asking here.

https://github.com/espressif/esp-idf/issues
